### ISSUE TITLE
can not read nav from c++ tools

### ISSUE THREAD

**Issue by matrix3d** [piotr-piastucki/recast4j#3]
https://github.com/matrix3d/recast4j/blob/master/src/test/all_tiles_navmesh.bin

**Comment by piotr-piastucki** [comment]
This should be now supported - see MeshSetReader class and MeshSetReaderTest. Please keep in mind that only 64-bit ref IDs are supported.

**Comment by matrix3d** [comment]
why only 64-bit?
https://github.com/matrix3d/recast4j/blob/master/src/org/recast4j/detour/NavMesh.as#L234

**Comment by piotr-piastucki** [comment]
This is a design decision as I do not see any benefits of using 32-bit ref IDs in Java. 
In Detour it is a compile-time setting (https://github.com/recastnavigation/recastnavigation/blob/master/Detour/Include/DetourNavMesh.h#L28) which probably allows to save some memory when 32-bit IDs are used, but in Java we will end up using long in both cases. 
I guess it might be a valid enhancement to add a possibility to read 32-bit refs from files and convert them to 64 bits on the fly.

**Comment by matrix3d** [comment]
so,the MeshSetReaderTest,can not read the 
https://github.com/matrix3d/recast4j/blob/master/src/test/all_tiles_navmesh.bin
just can read the 64bit copy?

**Comment by piotr-piastucki** [comment]
If the file was saved with 32-bit IDs (ant it looks like it was) it cannot be currently read by MeshSetReader. Unfortunately, Detour format does not provide any information about the size of IDs or even endianess (!) and you have to pass them manually to the reader. IMHO, the format should either use version field properly or add another field that describes the actual format or enforce one and only encoding to be used consistently.

**Comment by piotr-piastucki** [comment]
FYI: I have just added support for reading 32-bit files in https://github.com/piotr-piastucki/recast4j/commit/eb2f74aeb05bf835755f70aa4d9861ca823c8e4e.
